SELECT
    t1.ID AS account_id,

    INITCAP(t1.NAME) AS account_name,

    LEFT(TRIM(CAST(t1.ZIPCODE AS VARCHAR)), 5) AS Zip_code,

    t1.* EXCLUDE (ID, NAME, TYPE, LATEST_METADATA_PUB_DATE, ZIPCODE,
    AVG_VISITORS_PERCENT_BY_FREQ_1, AVG_VISITORS_PERCENT_BY_FREQ_2, AVG_VISITORS_PERCENT_BY_FREQ_3, 
    AVG_VISITORS_PERCENT_BY_FREQ_4, AVG_VISITORS_PERCENT_BY_FREQ_5, AVG_VISITORS_PERCENT_BY_FREQ_6,
    AVG_VISITORS_PERCENT_BY_FREQ_7, AVG_VISITORS_PERCENT_BY_FREQ_8, AVG_VISITORS_PERCENT_BY_FREQ_9,
    AVG_VISITORS_PERCENT_BY_FREQ_10, AVG_VISITORS_PERCENT_BY_FREQ_15, AVG_VISITORS_PERCENT_BY_FREQ_20,
    AVG_VISITORS_PERCENT_BY_FREQ_30_OR_MORE) 
    
FROM {{ ref('base_traffic_and_depl_all_metrics') }} t1

WHERE
    t1.ID IS NOT NULL 
    AND t1.TOTAL_DEPLETIONS_R12 IS NOT NULL