SELECT
    UPPER(t1.ID) AS account_id,
    UPPER(t1.NAME) AS account_name,

    UPPER(t1.CATEGORY) AS category,
    UPPER(t1.SUB_CATEGORY) AS sub_category,
    UPPER(t1.CATEGORY_GROUP) AS category_group,
    UPPER(t1.ADDRESS) AS address,
    LEFT(TRIM(CAST(t1.ZIPCODE AS VARCHAR)), 5) AS zip_code,
    UPPER(t1.STATE_NAME) AS state_name,
    UPPER(t1.COUNTRY) AS country,
    UPPER(t1.VISIT_DURATION_SEGMENTATION) AS visit_duration_segmentation,

    t1.* EXCLUDE (
        ID, 
        NAME, 
        ZIPCODE, 
        TYPE, 
        LATEST_METADATA_PUB_DATE,
        CATEGORY, 
        SUB_CATEGORY, 
        CATEGORY_GROUP, 
        ADDRESS, 
        STATE_NAME, 
        COUNTRY, 
        VISIT_DURATION_SEGMENTATION,
        AVG_VISITORS_PERCENT_BY_FREQ_1, 
        AVG_VISITORS_PERCENT_BY_FREQ_2, 
        AVG_VISITORS_PERCENT_BY_FREQ_3, 
        AVG_VISITORS_PERCENT_BY_FREQ_4, 
        AVG_VISITORS_PERCENT_BY_FREQ_5, 
        AVG_VISITORS_PERCENT_BY_FREQ_6,
        AVG_VISITORS_PERCENT_BY_FREQ_7, 
        AVG_VISITORS_PERCENT_BY_FREQ_8, 
        AVG_VISITORS_PERCENT_BY_FREQ_9,
        AVG_VISITORS_PERCENT_BY_FREQ_10, 
        AVG_VISITORS_PERCENT_BY_FREQ_15, 
        AVG_VISITORS_PERCENT_BY_FREQ_20,
        AVG_VISITORS_PERCENT_BY_FREQ_30_OR_MORE
    ) 
    
FROM {{ ref("base_traffic_and_depl_all_metrics") }} t1

WHERE
    t1.ID IS NOT NULL
    AND t1.TOTAL_DEPLETIONS_R12 IS NOT NULL
    AND (t1.TOTAL_YEARLY_FOOT_TRAFFIC IS NOT NULL OR t1.TOTAL_YEARLY_FOOT_TRAFFIC = 0)